CONFIG_ZMK_KEYBOARD_NAME="Sysless Corne"

# Milliseconds of inactivity before entering idle state
CONFIG_ZMK_IDLE_TIMEOUT=30000

# Enable deep sleep support
CONFIG_ZMK_SLEEP=y
# Milliseconds of inactivity before entering deep sleep
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=900000

# Fix iOS/iPadOS https://github.com/zmkfirmware/zmk/issues/378
CONFIG_ZMK_HID_CONSUMER_REPORT_USAGES_BASIC=y