manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: b17d896c5c30dbb038de36e7ed540318f9b048a1
      import: app/west.yml
  self:
    path: config
