manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: ee1e13510410e9b482fd20acf112bc3f1466c362
      import: app/west.yml
  self:
    path: config
